In [2]:
print("Hello UAV IDS")

Hello UAV IDS

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from pathlib import Path


def find_data_file():
    candidates = [
        Path.cwd() / "data" / "UAVIDS-2025.csv",
        Path.cwd().parent / "data" / "UAVIDS-2025.csv",
        Path("data/UAVIDS-2025.csv"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError("Could not find data/UAVIDS-2025.csv. Check that the file exists in the project data folder.")


data_path = find_data_file()
df = pd.read_csv(data_path)

print("Loaded dataset from:", data_path)
print(df.head())
print("\nShape:", df.shape)
print("\nColumns:", list(df.columns))

Loaded dataset from: c:\Users\hp\OneDrive\Desktop\uav network intrusion\AI-UAV-IDS\data\UAVIDS-2025.csv
   FlowID  FlowDuration/s        SrcAddr  SrcPort       DstAddr  DstPort  \
0       1         175.007  192.168.0.150        9  192.168.0.16        9
1       2         175.008  192.168.0.150        9  192.168.0.19        9
2       3         175.010  192.168.0.150        9  192.168.0.24        9
3       4         175.014  192.168.0.150        9  192.168.0.34        9
4       5         175.017  192.168.0.150        9  192.168.0.39        9

  Protocol  TxPackets  RxPackets  LostPackets  ...  RxPacketRate/s  \
0      UDP        251        215           36  ...         1.22853
1      UDP        251        223           28  ...         1.27423
2      UDP        251        224           27  ...         1.27993
3      UDP        251        212           39  ...         1.21133
4      UDP        251        215           36  ...         1.22845

   TxByteRate/s  RxByteRate/s  MeanDelay/s  MeanJitter/s  Throughput/Kbps  \
0       109.002       93.3679     0.022152      0.024406         0.746943
1       109.001       96.8411     0.019637      0.018678         0.774729
2       108.999       97.2744     0.023701      0.023917         0.778195
3       108.997       92.0614     0.034014      0.025408         0.736491
4       108.995       93.3623     0.034396      0.024933         0.746899

   MeanPacketSize  PacketDropRate  AverageHopCount         label
0              76        0.143426         0.074419  Sybil Attack
1              76        0.111554         0.053812  Sybil Attack
2              76        0.107570         0.044643  Sybil Attack
3              76        0.155378         0.033019  Sybil Attack
4              76        0.143426         0.009302  Sybil Attack

[5 rows x 23 columns]

Shape: (122171, 23)

Columns: ['FlowID', 'FlowDuration/s', 'SrcAddr', 'SrcPort', 'DstAddr', 'DstPort', 'Protocol', 'TxPackets', 'RxPackets', 'LostPackets', 'TxBytes', 'RxBytes', 'TxPacketRate/s', 'RxPacketRate/s', 'TxByteRate/s', 'RxByteRate/s', 'MeanDelay/s', 'MeanJitter/s', 'Throughput/Kbps', 'MeanPacketSize', 'PacketDropRate', 'AverageHopCount', 'label']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122171 entries, 0 to 122170
Data columns (total 20 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   FlowDuration/s   122171 non-null  float64
 1   SrcPort          122171 non-null  int64
 2   DstPort          122171 non-null  int64
 3   Protocol         122171 non-null  object
 4   TxPackets        122171 non-null  int64
 5   RxPackets        122171 non-null  int64
 6   LostPackets      122171 non-null  int64
 7   TxBytes          122171 non-null  int64
 8   RxBytes          122171 non-null  int64
 9   TxPacketRate/s   122171 non-null  float64
 10  RxPacketRate/s   122171 non-null  float64
 11  TxByteRate/s     122171 non-null  float64
 12  RxByteRate/s     122171 non-null  float64
 13  MeanDelay/s      122171 non-null  float64
 14  MeanJitter/s     122171 non-null  float64
 15  Throughput/Kbps  122171 non-null  float64
 16  MeanPacketSize   122171 non-null  int64
 17  PacketDropRate   122171 non-null  float64
 18  AverageHopCount  122171 non-null  float64
 19  label            122171 non-null  object
dtypes: float64(10), int64(8), object(2)
memory usage: 18.6+ MB

In [8]:
print(df['label'].value_counts())

label
Normal Traffic      26172
Blackhole Attack    26110
Wormhole Attack     26086
Sybil Attack        24077
Flooding Attack     19726
Name: count, dtype: int64

In [9]:
df = df.drop(['FlowID', 'SrcAddr', 'DstAddr'], axis=1)

In [13]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [12]:
df = df.drop_duplicates()

In [16]:
df.shape

(113952, 20)

In [17]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()


df['Protocol'] = le.fit_transform(df['Protocol'])


df['label'] = le.fit_transform(df['label'])

In [18]:
print(df[['Protocol', 'label']].head())

   Protocol  label
0         0      3
1         0      3
2         0      3
3         0      3
4         0      3

In [19]:
df.head()

,FlowDuration/s,SrcPort,DstPort,Protocol,TxPackets,RxPackets,LostPackets,TxBytes,RxBytes,TxPacketRate/s,RxPacketRate/s,TxByteRate/s,RxByteRate/s,MeanDelay/s,MeanJitter/s,Throughput/Kbps,MeanPacketSize,PacketDropRate,AverageHopCount,label
0,175.007,9,9,0,251,215,36,19076,16340,1.43423,1.22853,109.002,93.3679,0.022152,0.024406,0.746943,76,0.143426,0.074419,3
1,175.008,9,9,0,251,223,28,19076,16948,1.43422,1.27423,109.001,96.8411,0.019637,0.018678,0.774729,76,0.111554,0.053812,3
2,175.010,9,9,0,251,224,27,19076,17024,1.43420,1.27993,108.999,97.2744,0.023701,0.023917,0.778195,76,0.107570,0.044643,3
3,175.014,9,9,0,251,212,39,19076,16112,1.43417,1.21133,108.997,92.0614,0.034014,0.025408,0.736491,76,0.155378,0.033019,3
4,175.017,9,9,0,251,215,36,19076,16340,1.43415,1.22845,108.995,93.3623,0.034396,0.024933,0.746899,76,0.143426,0.009302,3

In [20]:
df.tail()

,FlowDuration/s,SrcPort,DstPort,Protocol,TxPackets,RxPackets,LostPackets,TxBytes,RxBytes,TxPacketRate/s,RxPacketRate/s,TxByteRate/s,RxByteRate/s,MeanDelay/s,MeanJitter/s,Throughput/Kbps,MeanPacketSize,PacketDropRate,AverageHopCount,label
122163,3467.7000,9,9,0,8685,8413,274,660060,639388,2.50454,2.42610,190.345,184.384,0.072202,0.061138,1.47507,76,0.031549,0.083442,1
122167,3442.8000,9,9,0,8763,8432,331,665988,640832,2.54531,2.44917,193.444,186.137,0.058090,0.053904,1.48909,76,0.037773,0.083610,1
122168,27.9001,9,9,0,94,94,0,7144,7144,3.36917,3.36917,256.057,256.057,0.000877,0.000833,2.04845,76,0.000000,0.000000,1
122169,27.9007,9,9,0,94,94,0,7144,7144,3.36909,3.36909,256.051,256.051,0.001339,0.000880,2.04841,76,0.000000,0.021277,1
122170,25.2010,9,9,0,66,66,0,5016,5016,2.61895,2.61895,199.040,199.040,0.002183,0.001396,1.59232,76,0.000000,0.000000,1

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numeric_cols = df.drop(columns=['label']).select_dtypes(include=[np.number]).columns

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("Scaled numeric feature columns:", list(numeric_cols))
df.head()

Scaled numeric feature columns: ['FlowDuration/s', 'SrcPort', 'DstPort', 'Protocol', 'TxPackets', 'RxPackets', 'LostPackets', 'TxBytes', 'RxBytes', 'TxPacketRate/s', 'RxPacketRate/s', 'TxByteRate/s', 'RxByteRate/s', 'MeanDelay/s', 'MeanJitter/s', 'Throughput/Kbps', 'MeanPacketSize', 'PacketDropRate', 'AverageHopCount']

,FlowDuration/s,SrcPort,DstPort,Protocol,TxPackets,RxPackets,LostPackets,TxBytes,RxBytes,TxPacketRate/s,RxPacketRate/s,TxByteRate/s,RxByteRate/s,MeanDelay/s,MeanJitter/s,Throughput/Kbps,MeanPacketSize,PacketDropRate,AverageHopCount,label
0,-0.691536,-0.602276,-0.602276,0.0,-0.093926,-0.124326,-0.020981,-0.104021,-0.121415,-0.006818,-0.000612,-0.006269,-0.000222,-0.419084,-0.381586,-0.000222,0.596404,-0.774569,-0.295774,3
1,-0.691535,-0.602276,-0.602276,0.0,-0.093926,-0.117631,-0.027705,-0.104021,-0.114590,-0.006818,0.000136,-0.006269,0.000526,-0.424667,-0.399711,0.000526,0.596404,-0.878083,-0.326649,3
2,-0.691532,-0.602276,-0.602276,0.0,-0.093926,-0.116795,-0.028545,-0.104021,-0.113737,-0.006818,0.000229,-0.006269,0.000620,-0.415645,-0.383134,0.000619,0.596404,-0.891022,-0.340386,3
3,-0.691527,-0.602276,-0.602276,0.0,-0.093926,-0.126837,-0.018460,-0.104021,-0.123975,-0.006818,-0.000894,-0.006269,-0.000504,-0.392742,-0.378415,-0.000504,0.596404,-0.735751,-0.357801,3
4,-0.691523,-0.602276,-0.602276,0.0,-0.093926,-0.124326,-0.020981,-0.104021,-0.121415,-0.006818,-0.000614,-0.006270,-0.000224,-0.391894,-0.379916,-0.000224,0.596404,-0.774569,-0.393334,3